---
- hosts: default
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    public_ip: 192.168.27.100
    version: stable/liberty
    neutron: True
    swift: True
    security_groups: False
    tempest: False
    keyring_config_dir: /home/vagrant/.local/share/python_keyring
    auth_url: http://{{ public_ip }}:5000/v2.0
    password: stack
    token: "{{ password }}"
    memcached:
      install_development_headers: true

  tasks:
    - name: create keyring config directory
      file: >
        state=directory
        dest={{ keyring_config_dir }}

    - name: copy keyring config file to workaround https://bugs.launchpad.net/bugs/1242992
      copy: >
        src=files/keyringrc.cfg
        dest={{ keyring_config_dir }}/keyringrc.cfg

    - name: install git
      apt: "name=git update_cache=yes"
      sudo: True

    - name: checkout devstack
      git: "repo={{ devstack_repo }} dest=/home/vagrant/devstack version={{ version }} accept_hostkey=yes"


    - name: local.conf
      template: src=templates/local.conf.j2 dest=/home/vagrant/devstack/local.conf

    - name: source openrc in profile
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'

    - name: enable eth2
      command: ip link set dev eth2 up
      sudo: True

    - debug: msg="checking if devstack is running"

    - action: uri url=http://127.0.0.1:80 return_content=yes
      register: webpage
      ignore_errors: yes

    - debug: msg="devstack not running"
      when: webpage|failed

    - name: boot up devstack
      command: /home/vagrant/devstack/stack.sh
      when: webpage|failed

    - debug: msg="booting up devstack"
      when: webpage|failed

    - name: keystone policy file
      template: src=templates/v3cloudsample.json.j2 dest=/etc/keystone/policy.json
      notify:
        - restart apache


    - name: get admin id
      shell: mysql -u root -D keystone -e "select id from user where name='admin'" --skip-column-names --silent
      register: admin_user_id_result

    - name: get admin role id
      shell: mysql -u root -D keystone -e "select id from role where name='admin'" --skip-column-names --silent
      register: admin_role_id_result

    - name: Get the default role name
      shell:  mysql -D keystone -e 'select name from role where name like "%ember";' --skip-column-names --silent
      register: default_role_result

    - name: add domain role to admin
      uri: url="http://{{ public_ip }}:5000/v3/domains/default/users/{{ admin_user_id_result.stdout }}/roles/{{ admin_role_id_result.stdout }}" method="PUT" HEADER_X-Auth-Token="{{ token }}" status_code=204


    - name: Install memcached server
      apt: pkg=memcached state=installed update-cache=yes
      sudo: True
      tags:
        - packages

    - name: Install header files
      apt: pkg=libmemcached-dev  state=installed update-cache=yes
      sudo: True
      when: memcached.install_development_headers == true
      tags:
        - packages

    - name: Install configuration file
      template: src=templates/memcached.conf.j2 dest=/etc/memcached.conf
      sudo: True
      notify: restart memcached
      tags:
        - configuration
    # Example action to restart service httpd, in all cases
    - name: restart memcached
      service: name=memcached state=restarted

    - debug: msg="admin user = {{admin_user_id_result.stdout}}".

    - debug: msg="admin role = {{admin_role_id_result.stdout}}"

    - debug: msg="default role = {{default_role_result.stdout}}"

    - debug: msg="OPENSTACK_HOST = {{public_ip}}"

    - name: Get ports on bridge br-ex
      shell: sudo ovs-vsctl list-ports br-ex
      register: ports_result


    - name: Add eth2 to br-ex
      shell: sudo ovs-vsctl add-port br-ex eth2
      when: "'eth2' not in ports_result.stdout"

    - name: restart memcache
      service: name=memcached state=restarted

  handlers:
    - name: restart memcached
      service: name=memcached state=restarted
    - name: restart apache
      service: name=apache2 state=restarted
      sudo: True
